//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGalleryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.DataRelations = new HashSet<DataRelation>();
        }
    
        public int ArtID { get; set; }
        public string ArtTitle { get; set; }
        public string ArtistName { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public decimal Price { get; set; }
        public string Discount { get; set; }
        public bool IsAvailable { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataRelation> DataRelations { get; set; }
    }
}
